repos:
  - repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
    - id: black
      language_version: python3.8
      args: [
        "-l", "92",
        "--target-version", "py38"
      ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: requirements-txt-fixer
    - id: mixed-line-ending
  - repo: https://github.com/pycqa/pylint
    rev: v2.9.3
    hooks:
    - id: pylint
      args: [
        "--disable=import-error,too-many-locals,too-many-locals,too-many-branches,too-many-statements",
        "--disable=too-many-arguments,too-many-instance-attributes"
      ]
      exclude: (?x)^(test_(.+)|time_(.+))$